<a href="https://colab.research.google.com/github/Pranay2638/NumpyProject/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

data = np.genfromtxt('Advertising.csv',delimiter = ',', skip_header = 1)

print(data.shape)
print(data[:5])

(200, 6)
[[  1.  230.1  37.8  69.2  22.1   nan]
 [  2.   44.5  10.5  45.1  10.4   nan]
 [  3.   17.2  45.9  69.3   9.3   nan]
 [  4.  151.5  41.3  58.5  18.5   nan]
 [  5.  180.8  10.8  58.4  12.9   nan]]


In [ ]:
import pandas as pd
df = pd.read_csv('Advertising.csv')
df

Unnamed: 0     TV  Radio  Newspaper  Sales channel
0             1  230.1   37.8       69.2   22.1  Visual
1             2   44.5   10.5       45.1   10.4   Print
2             3   17.2   45.9       69.3    9.3   Print
3             4  151.5   41.3       58.5   18.5  Visual
4             5  180.8   10.8       58.4   12.9  Visual
..          ...    ...    ...        ...    ...     ...
195         196   38.2    3.7       13.8    7.6  Visual
196         197   94.2    4.9        8.1    9.7  Visual
197         198  177.0    9.3        6.4   12.8  Visual
198         199  283.6   42.0       66.2   25.5  Visual
199         200  232.1    8.6        8.7   13.4  Visual

[200 rows x 6 columns]

In [ ]:
# Find the mean, median, and standard deviation of the Sales column.
sales = data[:,4]
mean = np.mean(sales)
print(mean)

median = np.median(sales)
print(median)

sd = np.std(sales)
print(sd)

14.0225
12.9
5.204396578855228


In [ ]:
# Which advertising channel (TV, Radio, Newspaper) has the highest average spending?
tv = data[:,1]
tv_mean = np.mean(tv)
radio = data[:,2]
radio_mean = np.mean(radio)
newspaper = data[:,3]
newspaper_mean = np.nanmean(newspaper)

if tv_mean > radio_mean and tv_mean > newspaper_mean:
  print("tv has higest average spending",tv_mean)
elif radio_mean > tv_mean and radio_mean > newspaper_mean:
  print("radio has highest average spending",radio_mean)
else:
  print("Newspaper has highest average spending",newspaper_mean)


Newspaper has highest average spending 30.610552763819097


In [ ]:
# Count how many campaigns have Sales greater than 20.
sales_count = data[:,4]
mask = sales_count > 20
print(data[mask])
print(np.sum(mask))


[[  1.  230.1  37.8  69.2  22.1   nan]
 [ 16.  195.4  47.7  52.9  22.4   nan]
 [ 18.  281.4  39.6  55.8  24.4   nan]
 [ 31.  292.9  28.3  43.2  21.4   nan]
 [ 37.  266.9  43.8   5.   25.4   nan]
 [ 40.  228.   37.7  32.   21.5   nan]
 [ 43.  293.6  27.7   1.8  20.7   nan]
 [ 48.  239.9  41.5  18.5  23.2   nan]
 [ 53.  216.4  41.7  39.6  22.6   nan]
 [ 54.  182.6  46.2  58.7  21.2   nan]
 [ 55.  262.7  28.8  15.9  20.2   nan]
 [ 56.  198.9  49.4  60.   23.7   nan]
 [ 59.  210.8  49.6  37.7  23.8   nan]
 [ 62.  261.3  42.7  54.7  24.2   nan]
 [ 70.  216.8  43.9  27.2  22.3   nan]
 [ 85.  213.5  43.   33.8  21.7   nan]
 [ 94.  250.9  36.5  72.3  22.2   nan]
 [ 99.  289.7  42.3  51.2  25.4   nan]
 [102.  296.4  36.3 100.9  23.8   nan]
 [105.  238.2  34.3   5.3  20.7   nan]
 [112.  241.7  38.   23.2  21.8   nan]
 [129.  220.3  49.    3.2  24.7   nan]
 [138.  273.7  28.9  59.7  20.8   nan]
 [140.  184.9  43.9   1.7  20.7   nan]
 [143.  220.5  33.2  37.9  20.1   nan]
 [148.  243.2  49.   44.3

In [ ]:
# Extract all rows where:

# TV > 200

# Sales > 15

# Return the number of such campaigns.

tv = data[:,1]
sales = data[:,4]

mask1 = tv > 200
mask2 = sales > 15
ans = mask1 & mask2
print(data[ans])
print(np.sum(ans))
# print(np.array([ans]))

[[  1.  230.1  37.8  69.2  22.1   nan]
 [ 12.  214.7  24.    4.   17.4   nan]
 [ 15.  204.1  32.9  46.   19.    nan]
 [ 18.  281.4  39.6  55.8  24.4   nan]
 [ 21.  218.4  27.7  53.4  18.    nan]
 [ 24.  228.3  16.9  26.2  15.5   nan]
 [ 28.  240.1  16.7  22.9  15.9   nan]
 [ 29.  248.8  27.1  22.9  18.9   nan]
 [ 31.  292.9  28.3  43.2  21.4   nan]
 [ 34.  265.6  20.    0.3  17.4   nan]
 [ 37.  266.9  43.8   5.   25.4   nan]
 [ 40.  228.   37.7  32.   21.5   nan]
 [ 41.  202.5  22.3  31.6  16.6   nan]
 [ 43.  293.6  27.7   1.8  20.7   nan]
 [ 48.  239.9  41.5  18.5  23.2   nan]
 [ 53.  216.4  41.7  39.6  22.6   nan]
 [ 55.  262.7  28.8  15.9  20.2   nan]
 [ 59.  210.8  49.6  37.7  23.8   nan]
 [ 60.  210.7  29.5   9.3  18.4   nan]
 [ 62.  261.3  42.7  54.7  24.2   nan]
 [ 63.  239.3  15.5  27.3  15.7   nan]
 [ 69.  237.4  27.5  11.   18.9   nan]
 [ 70.  216.8  43.9  27.2  22.3   nan]
 [ 75.  213.4  24.6  13.1  17.    nan]
 [ 85.  213.5  43.   33.8  21.7   nan]
 [ 94.  250.9  36.5  72.3

In [ ]:
sales = data[:,4]
tv = data[:,1]
radio = data[:,2]
newspaper = data[:,3]
effeciency = sales / (tv + radio + newspaper)
idx = np.argsort(effeciency)
top5_idx = idx[-5:]
print(data[top5_idx])

[[ 68.    nan  14.5  10.2  13.4   nan]
 [149.   38.    nan  11.9  10.9   nan]
 [ 93.    nan  33.5  59.   19.4   nan]
 [109.    nan   0.4  25.6   5.3   nan]
 [ 78.  120.5   nan  14.2  14.2   nan]]


In [ ]:
# Calculate the correlation coefficient between:

# TV & Sales

# Radio & Sales

# Newspaper & Sales
tv = data[:,1]
sales = data[:,4]
radio = data[:,2]
newspaper = data[:,3]
mask = ~np.isnan(tv) & ~np.isnan(sales) & ~np.isnan(radio) & ~np.isnan(newspaper)
tv_clean = tv[mask]
sales_clean = sales[mask]
radio_clean = radio[mask]
newspaper_clean = newspaper[mask]
corr_tv_sales = np.corrcoef(tv_clean,sales_clean)[0,1]

corr_radio_sales = np.corrcoef(radio_clean,sales_clean)[0,1]

corr_newspaper_sales = np.corrcoef(newspaper_clean, sales_clean)[0,1]

corr = np.array([corr_tv_sales,corr_radio_sales,corr_newspaper_sales])

channels = np.array(["TV","Radio","Newspaper"])

idx = np.argmax(corr)

print(channels[idx] , "has the highest correlation with sales: ", corr[idx])


TV has the highest correlation with sales:  0.7786426254573999


In [ ]:
# Normalization challenge
# Normalize TV, Radio, and Newspaper columns using min-max normalization:
# (x - min) / (max - min)
# Return a new NumPy array with normalized values.

tv = data[:,1]
radio = data[:,2]
newspaper = data[:,3]

tv_min = np.nanmin(tv)
tv_max = np.nanmax(tv)
radio_min = np.nanmin(radio)
radio_max = np.nanmax(radio)
newspaper_min = np.nanmin(newspaper)
newspaper_max = np.nanmax(newspaper)

tv_norm = (tv - tv_min)/(tv_max - tv_min)
radio_norm = (radio - radio_min)/(radio_max - radio_min)
newspaper_norm = (newspaper - newspaper_min)/(newspaper_max - newspaper_min)

norm_val = np.column_stack([tv_norm,radio_norm,newspaper_norm])
norm_val

array([[0.77578627, 0.76209677, 0.60598065],
       [0.1481231 , 0.21169355, 0.39401935],
       [0.0557998 , 0.92540323, 0.60686016],
       [0.50997633, 0.83266129, 0.51187335],
       [0.60906324, 0.21774194, 0.51099384],
       [0.02705445, 0.9858871 , 0.65699208],
       [0.19208657, 0.66129032, 0.20404573],
       [0.4041258 , 0.39516129, 0.09938434],
       [0.02671627, 0.04233871, 0.00615655],
       [0.67331755, 0.05241935, 0.18381706],
       [0.2211701 , 0.11693548, 0.21020229],
       [0.72370646, 0.48387097, 0.03254178],
       [0.07811972, 0.70766129, 0.5769569 ],
       [0.32735881, 0.15322581, 0.06068602],
       [0.68785932, 0.66330645, 0.40193492],
       [0.65843761, 0.96169355, 0.46262093],
       [0.22691917, 0.73790323, 1.        ],
       [0.94927291, 0.7983871 , 0.48812665],
       [0.2316537 , 0.41330645, 0.15831135],
       [0.49577274, 0.48185484, 0.16534741],
       [0.73621914, 0.55846774, 0.46701847],
       [0.80047345, 0.10282258, 0.20404573],
       [0.

In [ ]:
# Find campaigns where Sales is more than 2 standard deviations above the mean.
# Return:
# Number of such campaigns
# Their Sales values

sales = data[:,4]
sales_std = np.nanstd(sales)

mask =  sales > np.nanmean(sales) + 2 * sales_std
outliers = sales[mask]

print(outliers)
print(np.sum(mask))

[25.4 25.4 24.7 25.4 27.  26.2 25.5]
7


In [ ]:
# Find campaigns where:

# TV spending is above average

# BUT Sales are below average

tv = data[:,1]
sales = data[:,4]

tv_mean = np.nanmean(tv)
sales_mean = np.nanmean(sales)

mask = (tv > tv_mean) & (sales < sales_mean)

print(np.sum(mask))

26


In [ ]:
# Compare:
# 1️⃣ Average Sales when both TV and Radio spending are high
# 2️⃣ Overall average Sales

tv = data[:,1]
radio = data[:,2]
tv_avg = np.nanmean(tv)
radio_avg = np.nanmean(radio)
sales = data[:,4]
avg_sales = (tv > tv_avg) & (radio > radio_avg)
print(sales[avg_sales])
np.nanmean(sales[avg_sales])


[22.1 18.5 17.4 19.  22.4 24.4 18.  18.9 21.4 25.4 21.5 17.1 20.7 23.2
 22.6 21.2 20.2 23.7 23.8 18.4 24.2 18.9 22.3 18.3 17.  21.7 22.2 16.9
 25.4 23.8 20.7 19.8 21.8 19.7 24.7 19.6 20.8 20.7 19.2 20.1 25.4 16.6
 19.  18.  17.1 27.  20.2 26.2 22.6 17.3 17.3 25.5]


np.float64(20.959615384615383)

Working on new dataset

In [2]:
import numpy as np
data = np.genfromtxt('batting_stats_ipl.csv',delimiter = ',',skip_header = 1)

In [3]:
import pandas as pd
df = pd.read_csv('batting_stats_ipl.csv')
df.head(10)

Unnamed: 0          Batter  \
0           0  A Ashish Reddy   
1           1        A Badoni   
2           2      A Chandila   
3           3        A Chopra   
4           4     A Choudhary   
5           5     A Dananjaya   
6           6      A Flintoff   
7           7        A Kumble   
8           8       A Manohar   
9           9        A Mishra   

                                      Batter Team(s)  No. of Innings  \
0                Sunrisers Hyderabad/Deccan Chargers              22   
1                               Lucknow Super Giants              22   
2                                   Rajasthan Royals               2   
3                              Kolkata Knight Riders               6   
4                        Royal Challengers Bangalore               3   
5                                     Mumbai Indians               1   
6                                Chennai Super Kings               3   
7                        Royal Challengers Bangalore              15   
8                                     Gujarat Titans              13   
9  Delhi Daredevils/Sunrisers Hyderabad/Deccan Ch...              55   

   Not Outs  Total Runs  Balls Faced  No. of Outs  Batting Average  \
0         8         266          181           14        19.000000   
1         4         340          268           18        18.888889   
2         2           4            7            0         4.000000   
3         0          53           71            6         8.833333   
4         2          25           20            1        25.000000   
5         1           4            5            0         4.000000   
6         1          62           53            2        31.000000   
7        12          35           47            3        11.666667   
8         1         222          158           12        18.500000   
9        24         381          417           31        12.290323   

   Strike Rate  Balls Faced per Innings  Balls Faced per Wicket  
0   146.961326                 8.227273               12.928571  
1   126.865672                12.181818               14.888889  
2    57.142857                 3.500000                     inf  
3    74.647887                11.833333               11.833333  
4   125.000000                 6.666667               20.000000  
5    80.000000                 5.000000                     inf  
6   116.981132                17.666667               26.500000  
7    74.468085                 3.133333               15.666667  
8   140.506329                12.153846               13.166667  
9    91.366906                 7.581818               13.451613

In [ ]:
print(data.shape)

(637, 12)


In [4]:
# Q1️⃣ Batting overview
# Compute:
# Mean, median, std of Runs
# Mean Strike Rate

runs = data[:,5]
strike_rate = data[:,9]
mean = np.nanmean(runs)
median = np.nanmedian(runs)
std = np.nanstd(runs)
mean_SR = np.nanmean(strike_rate)
print(mean,median,std,mean_SR)

471.2480376766091 73.0 996.7743004217333 105.13530324703298


In [5]:
# How many players have Runs greater than the average Runs?

runs = data[:,5]
avg_runs = np.nanmean(runs)
players = runs > avg_runs
print(np.sum(players))

136


In [6]:
# Count how many players satisfy both conditions:
# Innings ≥ 20
# AND
# Average ≥ 30

Innings = data[:,3]
average = data[:,8]

players = (Innings >= 20) & (average >=30)
print(np.sum(players))

44


In [9]:
# Which players score runs efficiently WITHOUT relying on boundaries?

runs = data[:,5]
balls_faced = data[:,6]
strike_rate = data[:,9]

runs_per_ball = runs / balls_faced

mask = (runs_per_ball >= np.median(runs_per_ball)) & (strike_rate >= np.median(strike_rate))

print(np.sum(mask))

319


In [18]:
runs = data[:,5]
strike_rate = data[:,9]

players = (runs > np.median(runs)) & (strike_rate > np.median(strike_rate))

print(np.sum(players))
print(runs[players])
print(strike_rate[players])

249
[ 266.  340.  222.  974.  178.  123. 5001.  120. 2069.  181.  148.  723.
 2191. 2039.  775.  401.  672. 4254.   87.  339. 1400.  173. 4348.  372.
  886.   87.  134.  220.  186.  388.   76.  124.  507.  935. 2871.  238.
 1395.  179.  187.  452.  177.  303.  182. 1309. 4875.  618.  538.  949.
  169.  181.  161. 1467.  137. 2660. 6310.  304.  375.  170. 1560. 1278.
 1322.  295.  115.   80.  924. 1771. 2385.  460.  152.  653. 1371. 4133.
 4172.  724.  663. 2717.  505.  508.  190. 2264.  577.  230.  833.  158.
   96. 1079. 2170.  409.  962.  199. 3214.  604.  172.  614. 1217.  543.
  259. 1962.  503.  417.  226. 3293. 1656. 4408. 1442.  116. 1460. 4053.
 1170. 1001.  365.  199. 2003.  320.  128.   81.  302.  106. 1079.  392.
 1017.  817.  126.  426. 2598. 1073. 2490.  956.  237. 1977.  177.  255.
  278.   84.  402. 3712. 1695. 1074. 1034.  167. 1417.  604.  788. 5082.
   97.  394.  117. 1679.  117.  149. 1226. 2545.  241.  415. 1546.  506.
  361.  422. 2711.  277.  500.  203.  218.  379

In [17]:
# Detect players where:
# Runs > mean(Runs) + 2 × std(Runs)

mask = runs > np.nanmean(runs) + 2 * np.nanstd(runs)
print(np.sum(mask))
print(runs[mask])
print(strike_rate[mask])

37
[5001. 4254. 4348. 2871. 4875. 2660. 6310. 4133. 4172. 2717. 3214. 3293.
 4408. 4053. 2598. 2490. 3712. 5082. 2545. 2711. 2702. 2642. 6165. 2759.
 4941. 6573. 3195. 5512. 3796. 2674. 3835. 2750. 7122. 2702. 2754. 3162.
 2696.]
[152.0985401 123.3758701 128.2217635 132.9782307 150.2774353 138.325533
 140.6284823 134.4502277 124.5373134 159.3548387 149.0723562 146.6162066
 132.8511151 134.8303393 122.201317  134.4492441 120.7154472 136.6863905
 135.8782702 121.0808397 134.6959123 129.9557304 130.836163  150.1088139
 130.8874172 127.755102  144.2437923 137.5249501 138.641344  125.7761054
 137.4551971 135.5347462 130.6788991 157.6429405 127.618165  143.2065217
 129.7401347]


In [26]:
# Find the top 5 players with highest efficiency using np.argsort.
idx = np.argsort(runs_per_ball)
top5_idx = idx[-5:][::-1]
print("runs per ball: ",runs_per_ball[top5_idx])
print("Runs: ",runs[top5_idx])
print("strike rate: ", strike_rate[top5_idx])

runs per ball:  [2.5        2.05263158 2.         1.79661017 1.78632479]
Runs:  [  5.  39.   4. 106. 418.]
strike rate:  [250.        205.2631579 200.        179.6610169 178.6324786]


In [28]:
# Which players faced more balls than average but still scored fewer runs than average?

balls_faced = data[:,6]
runs = data[:,5]

mask = (balls_faced > np.nanmean(balls_faced)) & (runs < np.nanmean(runs))
print(np.sum(mask))
print("runs: ", runs[mask])
print("Strike rate: ", strike_rate[mask])

3
runs:  [381. 390. 460.]
Strike rate:  [ 91.36690647 100.         116.751269  ]


In [32]:
# Min–max normalize:
# Runs
# Balls
# Strike Rate

runs = data[:,5]
balls_faced = data[:,6]
strike_rate = data[:,9]

norm_runs = (runs - np.nanmin(runs)) / (np.nanmax(runs) - np.nanmin(runs))
norm_balls_faced = (balls_faced - np.nanmin(balls_faced)) / (np.nanmax(balls_faced) - np.nanmin(balls_faced))
norm_strike_rate = (strike_rate - np.nanmin(strike_rate)) / (np.nanmax(strike_rate) - np.nanmin(strike_rate))

total_norm = np.column_stack((norm_runs,norm_balls_faced,norm_strike_rate))
print(total_norm)
total_norm.shape

[[3.73490593e-02 3.30335841e-02 5.87845304e-01]
 [4.77393990e-02 4.89998165e-02 5.07462686e-01]
 [5.61639989e-04 1.10111947e-03 2.28571429e-01]
 ...
 [1.40409997e-04 1.83519912e-04 2.00000000e-01]
 [3.78545352e-01 3.81170857e-01 5.18960539e-01]
 [1.64279697e-02 2.55092678e-02 3.34285714e-01]]


(637, 3)

In [35]:
# Compare average Runs for players where:
# Strike Rate > median(Strike Rate)
# AND
# Runs > median(Runs)

strike_rate = data[:,9]
runs = data[:,5]

mask = (strike_rate > np.nanmedian(strike_rate)) & (runs > np.nanmedian(runs))

filtered_avg_runs = np.nanmean(runs[mask])
overall_avg_runs = np.nanmean(runs)



print(filtered_avg_runs)
print(overall_avg_runs)

1113.5823293172691
471.2480376766091
